### ISSUE TITLE
PHP notice if upgrading from earlier version of plugin

### ISSUE THREAD

**Issue by juiceboxint** [gyrus/Lock-Pages#2]
If upgrading the plugin (not installing it fresh), the array key for post types doesn't get added to the settings, which throws a notice on each admin page load.

It's fixable by going back to the options page and re-saving, but could be fixed in code as well. I added this to the load_options function to fix it automatically:

```
/**
 * Add empty array for post types if not present.
 * @since   0.3.1
 */
if ( ! array_key_exists( $this->prefix . 'post_types', $the_options ) ) {
    $the_options[ $this->prefix . 'post_types' ] = array();
    update_option( $this->options_name, $the_options );
}
```

**Comment by gyrus** [comment]
Thanks for pointing this out! Looking at it, it could probably do with a proper system for defaulting options on updates, to handle it whenever a new option's added. I've redone `load_options()` with this in mind:

https://github.com/gyrus/Lock-Pages/archive/c3201f735a2dcca74b21d549a9cac3ea75037dfd.zip

**Comment by juiceboxint** [comment]
Looks great to me! Thanks for fixing that.
